site_name: mc68k-manual
theme: readthedocs
use_directory_urls: false

markdown_extensions:
 - footnotes
 - extra

nav:
  - トップ: index.md
  - データサイズ: data-size.md
  - よくつかう命令: Frequent-command.md
  - アドレッシングモード: Frequent-addressing.md
  - スタック: Stack.md
  - Human68kシステムコール: dos-call.md
  - x68kツール: 
    - ED.X-テキストエディタ: tool-EDx.md
    - AS.X LK.X-アセンブラ リンカ: tool-ASxLKx.md
    - windrvXM.SYS-Windowsとのファイルやり取り: tool-windrvXMsys.md
    - VOL.X-ボリューム名変更: tool-VOLx.md
  - 設定:
    - パスを通す: setting-PATH.md
    - プロンプトにカレントパスを表示する: setting-promptCurPath.md